name=TR_ServoControl
version=0.1
author=Christian Pedersen <tinkerbug@tinkerbugrobotics.com>
maintainer=Christian Pedersen <tinkerbug@tinkerbugrobotics.com>
sentence=Arduino library for controlling roll with a servo
paragraph=
category=Controller
url=
architectures=*
includes=TR_ServoControl.h 
depends=
