M48
; DRILL file KiCad 10.0.3 date 2026-06-18T05:37:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-18T05:37:40-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.041
%
G90
G05
T1
X82.14Y-164.68
X87.92Y-164.68
T2
X79.06Y-105.525
X91.06Y-105.525
M30
