name=TR_PID
version=0.1
author=Christian Pedersen <tinkerbug@tinkerbugrobotics.com>
maintainer=Christian Pedersen <tinkerbug@tinkerbugrobotics.com>
sentence=Arduino library (SPI) implementing a simple PID contoller
paragraph=
category=Controller
url=
architectures=*
includes=TR_PID.h 
depends=
