// GENERATED by tools/gen_design_tokens.py from design/tokens.json -- DO NOT EDIT.
// Edit design/tokens.json, re-run the generator, commit both.

import SwiftUI
import UIKit

/// Semantic colors of the TinkerRocket design language.  iOS is the
/// design reference: these are the Apple system-color values the app
/// has always used, lifted into named roles so Android renders the
/// exact same hex (see the twin generated DesignTokens.kt).
enum TRColor {
    static let savedFlights = dynamic(0x007AFF, 0x0A84FF)  // blue
    static let myDevices = dynamic(0x5856D6, 0x5E5CE6)  // indigo
    static let driftCast = dynamic(0xFF3B30, 0xFF453A)  // red
    static let scan = dynamic(0x34C759, 0x30D158)  // green
    static let scanActive = dynamic(0xFF3B30, 0xFF453A)  // red
    static let camera = dynamic(0x007AFF, 0x0A84FF)  // blue
    static let logging = dynamic(0xFF9500, 0xFF9F0A)  // orange
    static let simulate = dynamic(0xFF9500, 0xFF9F0A)  // orange
    static let servoTest = dynamic(0x30B0C7, 0x40C8E0)  // teal
    static let freqScan = dynamic(0xAF52DE, 0xBF5AF2)  // purple
    static let mapControl = dynamic(0x007AFF, 0x0A84FF)  // blue
    static let statusConnected = dynamic(0x34C759, 0x30D158)  // green
    static let statusScanning = dynamic(0xFF9500, 0xFF9F0A)  // orange
    static let statusIdle = dynamic(0x8E8E93, 0x8E8E93)  // gray
    static let voiceReady = dynamic(0x34C759, 0x30D158)  // green
    static let voiceWarn = dynamic(0xFF9500, 0xFF9F0A)  // orange
    static let voiceError = dynamic(0xFF3B30, 0xFF453A)  // red
    static let orientWarn = dynamic(0xFF9500, 0xFF9F0A)  // orange
    static let signalBest = dynamic(0x007AFF, 0x0A84FF)  // blue
    static let signalGood = dynamic(0x34C759, 0x30D158)  // green
    static let signalFair = dynamic(0xFFCC00, 0xFFD60A)  // yellow
    static let signalWeak = dynamic(0xFF9500, 0xFF9F0A)  // orange
    static let signalBad = dynamic(0xFF3B30, 0xFF453A)  // red

    static let background = dynamic(0xFFFFFF, 0x000000)
    static let card = dynamic(0xF2F2F7, 0x1C1C1E)
    static let cardSecondary = dynamic(0xE5E5EA, 0x2C2C2E)

    private static func dynamic(_ light: UInt32, _ dark: UInt32) -> Color {
        Color(UIColor { traits in
            let v = traits.userInterfaceStyle == .dark ? dark : light
            return UIColor(
                red: CGFloat((v >> 16) & 0xFF) / 255.0,
                green: CGFloat((v >> 8) & 0xFF) / 255.0,
                blue: CGFloat(v & 0xFF) / 255.0,
                alpha: 1.0)
        })
    }
}

enum TRShape {
    static let radiusButton: CGFloat = 10
    static let radiusChip: CGFloat = 8
    static let radiusSheet: CGFloat = 12
}

enum TRSpacing {
    static let screenPadding: CGFloat = 16
    static let stackSpacing: CGFloat = 20
    static let rowSpacing: CGFloat = 12
    static let cardInnerSpacing: CGFloat = 12
    static let buttonPadV: CGFloat = 16
    static let compactPadH: CGFloat = 20
    static let compactPadV: CGFloat = 12
    static let statusDotSize: CGFloat = 12
}
