import Foundation
import XCTest

/// Access to the shared golden-vector corpus (tests_cpp/fixtures/wire/),
/// generated by the C++ emitter from the REAL packed firmware structs and
/// freshness-guarded by test_wire_fixture_freshness (android-port plan §2.1).
/// The Kotlin :core:protocol golden walk consumes the SAME files — layout
/// drift between any pair of C++/Swift/Kotlin fails one of the three suites.
///
/// Located via #filePath rather than a bundle folder reference: tests build
/// and run on the same machine as the checkout (local + CI), so the source
/// tree is present at test runtime and no pbxproj surgery is needed.
enum WireFixtures {

    static let root: URL = {
        // …/TinkerRocketApp/TinkerRocketAppTests/WireFixtures.swift → repo root
        var url = URL(fileURLWithPath: #filePath)
        url.deleteLastPathComponent()   // WireFixtures.swift
        url.deleteLastPathComponent()   // TinkerRocketAppTests
        url.deleteLastPathComponent()   // TinkerRocketApp
        return url.appendingPathComponent("tests_cpp/fixtures/wire")
    }()

    static func url(_ rel: String) -> URL {
        root.appendingPathComponent(rel)
    }

    static func data(_ rel: String, file: StaticString = #filePath, line: UInt = #line) -> Data {
        guard let d = try? Data(contentsOf: url(rel)) else {
            XCTFail("missing fixture \(rel) — build tests_cpp target regen-wire-fixtures",
                    file: file, line: line)
            return Data()
        }
        return d
    }

    /// The .expected.json sidecar for a .bin fixture.
    static func sidecar(_ rel: String, file: StaticString = #filePath, line: UInt = #line) -> [String: Any] {
        let side = rel.replacingOccurrences(of: ".bin", with: ".expected.json")
        guard let d = try? Data(contentsOf: url(side)),
              let obj = try? JSONSerialization.jsonObject(with: d) as? [String: Any] else {
            XCTFail("missing/invalid sidecar for \(rel)", file: file, line: line)
            return [:]
        }
        return obj
    }

    static func manifestEntries(file: StaticString = #filePath, line: UInt = #line) -> [[String: Any]] {
        guard let d = try? Data(contentsOf: url("manifest.json")),
              let obj = try? JSONSerialization.jsonObject(with: d) as? [String: Any],
              let fixtures = obj["fixtures"] as? [[String: Any]] else {
            XCTFail("missing/invalid manifest.json", file: file, line: line)
            return []
        }
        return fixtures
    }
}

// Sidecar value accessors — JSONSerialization vends NSNumber; these keep the
// call sites readable and the widths explicit.
extension Dictionary where Key == String, Value == Any {
    func int(_ k: String) -> Int { (self[k] as? NSNumber)?.intValue ?? .min }
    func i64(_ k: String) -> Int64 { (self[k] as? NSNumber)?.int64Value ?? .min }
    func u64(_ k: String) -> UInt64 { (self[k] as? NSNumber)?.uint64Value ?? .max }
    /// %.9g decimal text uniquely identifies a Float: Double-parse then
    /// round-to-Float recovers the exact stored value.
    func f32(_ k: String) -> Float { Float((self[k] as? NSNumber)?.doubleValue ?? .nan) }
    func str(_ k: String) -> String { self[k] as? String ?? "" }
    func ints(_ k: String) -> [Int] { (self[k] as? [NSNumber])?.map { $0.intValue } ?? [] }
}
