/* BeiDou B1C Weil-code parameters (core/sig/b1c_params.c, generated by py/gen_codes.py). */
#ifndef GNSS_SIG_B1C_PARAMS_H
#define GNSS_SIG_B1C_PARAMS_H

#include <stdint.h>

#define BDS_B1C_NPRN 63

/* {w, p} per PRN: the phase difference between the Legendre sequences and the truncation point. */
extern const uint16_t b1c_data_wp[BDS_B1C_NPRN][2];
extern const uint16_t b1c_pilot_wp[BDS_B1C_NPRN][2];
extern const uint16_t b1c_secondary_wp[BDS_B1C_NPRN][2];

#endif /* GNSS_SIG_B1C_PARAMS_H */
