/*
 * Galileo E1-B and E1-C primary codes (core/sig/gal_e1_codes.c, generated by py/gen_codes.py
 * from the Galileo OS SIS ICD). That data file carries the EU's terms and is not under this
 * repository's licence; see its header.
 */
#ifndef GNSS_SIG_GAL_E1_CODES_H
#define GNSS_SIG_GAL_E1_CODES_H

#include <stdint.h>

#define GAL_E1_NCODES     50
#define GAL_E1_CODE_BYTES 512   /* 4092 chips, chip 0 in the MSB of byte 0 */

extern const uint8_t gal_e1b_codes[GAL_E1_NCODES][GAL_E1_CODE_BYTES];
extern const uint8_t gal_e1c_codes[GAL_E1_NCODES][GAL_E1_CODE_BYTES];

#endif /* GNSS_SIG_GAL_E1_CODES_H */
