M48
; DRILL file KiCad 10.0.3 date 2026-06-13T07:37:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-13T07:37:28-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.550
%
G90
G05
T1
X60.17Y-189.028
X65.95Y-189.028
T2
X59.03Y-134.45
X59.03Y-138.85
T3
X66.89Y-185.7
T4
X50.89Y-177.5
X66.89Y-122.3
M30
