#!/usr/bin/env python3
"""Generates the spreading-code data the receiver needs from the official ICDs. Run it once per
ICD issue; the outputs are committed.

    gen_codes.py --gal-icd Galileo_OS_SIS_ICD_v2.0.pdf --b1c-icd BDS-SIS-ICD-B1C-1.0.pdf

- Galileo E1-B and E1-C primary codes are memory codes. The OS SIS ICD ships them as the
  attachments C7_E1B.txt and C8_E1C.txt of its PDF (Annex C). Issue 2.0 (2021) carries them;
  the Issue 2.1 (2023) file on gsc-europa.eu has no attachments, and the codes did not change.
  -> core/sig/gal_e1_codes.c, which carries the EU's terms: it is NOT under this repository's
     licence (see its header).
- BeiDou B1C codes are Weil codes; only their parameters come from the ICD (Tables 5-2, 5-3
  and 5-4 of BDS-SIS-ICD-B1C-1.0), and core/sig/codes.c generates the chips.
  -> core/sig/b1c_params.c, and tests/b1c_icd_chips.h: the ICD's first and last 24 chips of
     every code, which the unit tests check the generator against.

Needs pypdf and pdftotext (poppler).
"""
from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def gal_codes(pdf: Path) -> dict[str, list[str]]:
    import pypdf

    att = pypdf.PdfReader(str(pdf)).attachments
    out = {}
    for key, name in (("E1B", "C7_E1B.txt"), ("E1C", "C8_E1C.txt")):
        if name not in att:
            raise SystemExit(f"{pdf} has no attachment {name}: use Issue 2.0, whose PDF carries the codes")
        lines = [ln.strip() for ln in att[name][0].decode("ascii").splitlines() if ln.strip()]
        codes = []
        for k, ln in enumerate(lines, 1):
            label, hexs = ln.split(";")
            if label != f"{key}__Code_No_{k:02d}" or len(hexs) != 1023:
                raise SystemExit(f"{name}: unexpected line {k}: {label}, {len(hexs)} symbols")
            codes.append(hexs)
        if len(codes) != 50:
            raise SystemExit(f"{name}: {len(codes)} codes, not 50")
        out[key] = codes
    return out


def write_gal(codes: dict[str, list[str]], path: Path, pdf_name: str) -> None:
    def packed(hexs: str) -> list[int]:
        # 4092 chips = 1023 symbols = 511.5 bytes: chip 0 is the MSB of byte 0; the last
        # nibble is padded with zeros.
        b = bytes.fromhex(hexs + "0")
        assert len(b) == 512
        return list(b)

    lines = [
        "/*",
        " * Galileo E1-B and E1-C primary codes, generated by py/gen_codes.py; do not edit.",
        " *",
        " * Technical Data of the European GNSS (Galileo) Open Service Signal-In-Space Interface",
        f" * Control Document, Issue 2.0, Annex C (the PDF's attachments C7_E1B.txt and C8_E1C.txt,",
        f" * from {pdf_name}), (c) European Union 2021; the codes are unchanged in Issue 2.1",
        " * (c) European Union 2023. Source: https://www.gsc-europa.eu.",
        " *",
        " * NOT LICENSED UNDER THIS REPOSITORY'S LICENCE. The codes are stored and used under the",
        " * EU's Authorisation Concerning the OS SIS ICD IPRs (Annex G of Issue 2.0, Annex H of",
        " * Issue 2.1), which is non-transferable and non-licensable; whoever uses this file does so",
        " * under that Authorisation directly. Neither the EU nor the owners of the patents named",
        " * there developed, use or endorse this receiver.",
        " *",
        " * Packing: 512 bytes per code, chip 0 in the most significant bit of byte 0, a 1 bit is",
        " * the ICD's logic 1; the last 4 bits are padding.",
        " */",
        '#include "gal_e1_codes.h"',
        "",
    ]
    for key, var in (("E1B", "gal_e1b_codes"), ("E1C", "gal_e1c_codes")):
        lines.append(f"const uint8_t {var}[GAL_E1_NCODES][GAL_E1_CODE_BYTES] = {{")
        for k, hexs in enumerate(codes[key], 1):
            b = packed(hexs)
            lines.append(f"    /* PRN {k} */ {{")
            for j in range(0, 512, 16):
                lines.append("        " + ", ".join(f"0x{v:02X}" for v in b[j:j + 16]) + ",")
            lines.append("    },")
        lines.append("};")
        lines.append("")
    path.write_text("\n".join(lines))


B1C_ROW = re.compile(r"^\s*(\d{1,2})\s+(\d+)\s+(\d+)\s+([0-7]{8})\s+([0-7]{8})\s*$")
SECTION = re.compile(r"^\s*\d+(\.\d+)+\s+[A-Za-z]|^\s*\d+\s+[A-Z][a-z]+ [A-Za-z]")


def b1c_tables(pdf: Path) -> dict[str, list[tuple]]:
    text = subprocess.run(["pdftotext", "-layout", str(pdf), "-"], capture_output=True, text=True,
                          check=True).stdout.splitlines()

    def table(start: str, end: re.Pattern | str) -> list[tuple]:
        s = next(i for i, ln in enumerate(text) if start in ln)
        e = next(i for i in range(s + 1, len(text))
                 if (end in text[i] if isinstance(end, str) else end.search(text[i])))
        rows = []
        for ln in text[s:e]:
            m = B1C_ROW.match(ln)
            if m:
                rows.append((int(m.group(1)), int(m.group(2)), int(m.group(3)), m.group(4), m.group(5)))
        if [r[0] for r in rows] != list(range(1, 64)):
            raise SystemExit(f"{start}: PRNs {[r[0] for r in rows]}")
        return rows

    return {
        "data": table("Table 5-2 Primary code parameters of the B1C data", "Table 5-3"),
        "pilot": table("Table 5-3 Primary code parameters of the B1C pilot", "Table 5-4"),
        "secondary": table("Table 5-4 Secondary code parameters", SECTION),
    }


def write_b1c(tabs: dict[str, list[tuple]], params: Path, chips: Path) -> None:
    head = [
        "/*",
        " * BeiDou B1C Weil-code parameters, generated by py/gen_codes.py; do not edit.",
        " * From BDS-SIS-ICD-B1C-1.0 (China Satellite Navigation Office, December 2017),",
        " * Tables 5-2, 5-3 and 5-4: phase difference w and truncation point p per PRN.",
        " */",
    ]
    lines = head + ['#include "b1c_params.h"', ""]
    for key, var in (("data", "b1c_data_wp"), ("pilot", "b1c_pilot_wp"), ("secondary", "b1c_secondary_wp")):
        lines.append(f"const uint16_t {var}[BDS_B1C_NPRN][2] = {{")
        rows = tabs[key]
        for j in range(0, 63, 6):
            lines.append("    " + " ".join(f"{{{r[1]}, {r[2]}}}," for r in rows[j:j + 6]))
        lines.append("};")
        lines.append("")
    params.write_text("\n".join(lines))

    t = [
        "// The first and last 24 chips (octal, first chip in the MSB) of every B1C code, from",
        "// BDS-SIS-ICD-B1C-1.0 Tables 5-2 (data), 5-3 (pilot) and 5-4 (pilot secondary).",
        "// Generated by py/gen_codes.py; the unit tests check the generator against them.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace b1c_icd {",
    ]
    for key in ("data", "pilot", "secondary"):
        t.append(f"constexpr uint32_t {key}[63][2] = {{")
        rows = tabs[key]
        for j in range(0, 63, 4):
            t.append("    " + " ".join(f"{{0{r[3]}, 0{r[4]}}}," for r in rows[j:j + 4]))
        t.append("};")
    t.append("}  // namespace b1c_icd")
    t.append("")
    chips.write_text("\n".join(t))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--gal-icd", type=Path, required=True)
    ap.add_argument("--b1c-icd", type=Path, required=True)
    a = ap.parse_args()
    write_gal(gal_codes(a.gal_icd), ROOT / "core" / "sig" / "gal_e1_codes.c", a.gal_icd.name)
    write_b1c(b1c_tables(a.b1c_icd), ROOT / "core" / "sig" / "b1c_params.c", ROOT / "tests" / "b1c_icd_chips.h")
    print("wrote core/sig/gal_e1_codes.c, core/sig/b1c_params.c, tests/b1c_icd_chips.h")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
