name=TR_GPS_INS_Fusion_EKF
version=0.1
author=Christian Pedersen <tinkerbug@tinkerbugrobotics.com>
maintainer=Christian Pedersen <tinkerbug@tinkerbugrobotics.com>
sentence=Arduino library implementing an extended Kalman filter to fuse GPS and INS measurements
paragraph=
category=Controller
url=
architectures=*
includes=TR_GPS_INS_Fusion_EKF.h 
depends=
