package com.tinkerbug.tinkerrocket.protocol

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import java.io.File

/**
 * Access to the shared golden-vector corpus (tests_cpp/fixtures/wire/),
 * generated by the C++ emitter from the REAL packed firmware structs and
 * freshness-guarded by test_wire_fixture_freshness.  The Gradle test task
 * points tr.fixtures.dir at the monorepo location.
 */
object WireFixtures {
    val root: File by lazy {
        val p = System.getProperty("tr.fixtures.dir")
            ?: error("tr.fixtures.dir not set — run via Gradle")
        val dir = File(p)
        check(dir.isDirectory) {
            "golden corpus missing at $dir — build tests_cpp target regen-wire-fixtures"
        }
        dir
    }

    fun bytes(rel: String): ByteArray = File(root, rel).readBytes()

    fun sidecar(rel: String): JsonObject {
        val side = rel.removeSuffix(".bin") + ".expected.json"
        return Json.parseToJsonElement(File(root, side).readText()).jsonObject
    }

    fun manifest(): JsonObject =
        Json.parseToJsonElement(File(root, "manifest.json").readText()).jsonObject
}
