// :core:protocol — pure JVM, ZERO Android dependencies (android-port plan §1).
//
// Everything that touches wire bytes or firmware-mirrored math lives here so
// it is testable on a plain JVM against the C++-emitted golden vectors in
// tests_cpp/fixtures/wire/.  No android.* / androidx.* import may ever appear
// in this module — that boundary is also the future KMP commonMain seam.

plugins {
    kotlin("jvm")
}

kotlin {
    jvmToolchain(21)
    explicitApi()
}

dependencies {
    // TelemetryData decodes wire JSON via the JsonElement API with a
    // hand-written mapper (never plugin-default @Serializable — it cannot
    // express the per-field flexInt tolerance), so no serialization plugin.
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
    // The golden corpus lives in the monorepo, generated by
    // tests_cpp/wire_fixture_gen and guarded by test_wire_fixture_freshness.
    val fixturesDir = rootProject.projectDir.parentFile.resolve("tests_cpp/fixtures/wire")
    systemProperty("tr.fixtures.dir", fixturesDir.absolutePath)
    // CRITICAL: without this, Gradle's up-to-date/build-cache check does not
    // see fixture-content changes (the systemProperty is just a constant path
    // string) and would skip the golden walk exactly when the corpus changed —
    // silently defeating the three-way parity gate.
    inputs.dir(fixturesDir)
        .withPropertyName("wireFixtures")
        .withPathSensitivity(PathSensitivity.RELATIVE)
}
