// :core:protocol — pure JVM, ZERO Android dependencies (android-port plan §1).
//
// Everything that touches wire bytes or firmware-mirrored math lives here so
// it is testable on a plain JVM against the C++-emitted golden vectors in
// tests_cpp/fixtures/wire/.  No android.* / androidx.* import may ever appear
// in this module — that boundary is also the future KMP commonMain seam.

plugins {
    kotlin("jvm")
}

kotlin {
    jvmToolchain(21)
    explicitApi()
}

dependencies {
    testImplementation(kotlin("test"))
    // Sidecar (.expected.json) parsing in the golden walk. JsonElement API
    // only — no @Serializable classes yet, so no serialization plugin needed.
    testImplementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0")
}

tasks.test {
    useJUnitPlatform()
    // The golden corpus lives in the monorepo, generated by
    // tests_cpp/wire_fixture_gen and guarded by test_wire_fixture_freshness.
    systemProperty(
        "tr.fixtures.dir",
        rootProject.projectDir.parentFile.resolve("tests_cpp/fixtures/wire").absolutePath,
    )
}
