// GENERATED by tools/gen_design_tokens.py from design/tokens.json -- DO NOT EDIT.
// Edit design/tokens.json, re-run the generator, commit both.

package com.tinkerbug.tinkerrocket.app.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Semantic colors of the TinkerRocket design language.  iOS is the
 * design reference: these are the Apple system-color values the iOS
 * app renders, so the two apps match hue for hue (twin generated
 * file: DesignTokens.swift).  Screens reach for roles, never raw
 * palette colors.
 */
class TrColors(
    val savedFlights: Color,
    val myDevices: Color,
    val driftCast: Color,
    val scan: Color,
    val scanActive: Color,
    val camera: Color,
    val logging: Color,
    val simulate: Color,
    val servoTest: Color,
    val freqScan: Color,
    val mapControl: Color,
    val statusConnected: Color,
    val statusScanning: Color,
    val statusIdle: Color,
    val voiceReady: Color,
    val voiceWarn: Color,
    val voiceError: Color,
    val orientWarn: Color,
    val signalBest: Color,
    val signalGood: Color,
    val signalFair: Color,
    val signalWeak: Color,
    val signalBad: Color,
    val background: Color,
    val card: Color,
    val cardSecondary: Color,
)

val TrColorsLight = TrColors(
    savedFlights = Color(0xFF0088FF),  // blue
    myDevices = Color(0xFF6155F5),  // indigo
    driftCast = Color(0xFFFF383C),  // red
    scan = Color(0xFF34C759),  // green
    scanActive = Color(0xFFFF383C),  // red
    camera = Color(0xFF0088FF),  // blue
    logging = Color(0xFFFF8D28),  // orange
    simulate = Color(0xFFFF8D28),  // orange
    servoTest = Color(0xFF00C3D0),  // teal
    freqScan = Color(0xFFCB30E0),  // purple
    mapControl = Color(0xFF0088FF),  // blue
    statusConnected = Color(0xFF34C759),  // green
    statusScanning = Color(0xFFFF8D28),  // orange
    statusIdle = Color(0xFF8E8E93),  // gray
    voiceReady = Color(0xFF34C759),  // green
    voiceWarn = Color(0xFFFF8D28),  // orange
    voiceError = Color(0xFFFF383C),  // red
    orientWarn = Color(0xFFFF8D28),  // orange
    signalBest = Color(0xFF0088FF),  // blue
    signalGood = Color(0xFF34C759),  // green
    signalFair = Color(0xFFFFCC00),  // yellow
    signalWeak = Color(0xFFFF8D28),  // orange
    signalBad = Color(0xFFFF383C),  // red
    background = Color(0xFFFFFFFF),
    card = Color(0xFFF2F2F7),
    cardSecondary = Color(0xFFE5E5EA),
)

val TrColorsDark = TrColors(
    savedFlights = Color(0xFF0091FF),  // blue
    myDevices = Color(0xFF6D7CFF),  // indigo
    driftCast = Color(0xFFFF4245),  // red
    scan = Color(0xFF30D158),  // green
    scanActive = Color(0xFFFF4245),  // red
    camera = Color(0xFF0091FF),  // blue
    logging = Color(0xFFFF9230),  // orange
    simulate = Color(0xFFFF9230),  // orange
    servoTest = Color(0xFF00D2E0),  // teal
    freqScan = Color(0xFFDB34F2),  // purple
    mapControl = Color(0xFF0091FF),  // blue
    statusConnected = Color(0xFF30D158),  // green
    statusScanning = Color(0xFFFF9230),  // orange
    statusIdle = Color(0xFF8E8E93),  // gray
    voiceReady = Color(0xFF30D158),  // green
    voiceWarn = Color(0xFFFF9230),  // orange
    voiceError = Color(0xFFFF4245),  // red
    orientWarn = Color(0xFFFF9230),  // orange
    signalBest = Color(0xFF0091FF),  // blue
    signalGood = Color(0xFF30D158),  // green
    signalFair = Color(0xFFFFD600),  // yellow
    signalWeak = Color(0xFFFF9230),  // orange
    signalBad = Color(0xFFFF4245),  // red
    background = Color(0xFF000000),
    card = Color(0xFF1C1C1E),
    cardSecondary = Color(0xFF2C2C2E),
)

object TrShape {
    val radiusButton: Dp = 10.dp
    val radiusChip: Dp = 8.dp
    val radiusSheet: Dp = 12.dp
}

object TrSpacing {
    val screenPadding: Dp = 16.dp
    val stackSpacing: Dp = 20.dp
    val rowSpacing: Dp = 12.dp
    val cardInnerSpacing: Dp = 12.dp
    val buttonPadV: Dp = 16.dp
    val compactPadH: Dp = 20.dp
    val compactPadV: Dp = 12.dp
    val statusDotSize: Dp = 12.dp
}
