#!/usr/bin/env python3
"""Generate the platform design-token files from design/tokens.json.

iOS is the design reference (2026-07-30): the tokens carry the Apple
system-color values the iOS app has always rendered, and Android renders the
same hex instead of Material defaults.  This generator is the sync mechanism —
the same pattern as gen_section_index.py:

    python3 tools/gen_design_tokens.py           # write both files
    python3 tools/gen_design_tokens.py --check   # CI freshness gate

Outputs (GENERATED — never hand-edit):
    TinkerRocketApp/TinkerRocketApp/DesignTokens.swift
    TinkerRocketAndroid/app/src/main/kotlin/com/tinkerbug/tinkerrocket/app/theme/DesignTokens.kt
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOKENS = ROOT / "design" / "tokens.json"
SWIFT_OUT = ROOT / "TinkerRocketApp" / "TinkerRocketApp" / "DesignTokens.swift"
KOTLIN_OUT = (
    ROOT
    / "TinkerRocketAndroid"
    / "app"
    / "src"
    / "main"
    / "kotlin"
    / "com"
    / "tinkerbug"
    / "tinkerrocket"
    / "app"
    / "theme"
    / "DesignTokens.kt"
)

HEADER = (
    "GENERATED by tools/gen_design_tokens.py from design/tokens.json"
    " -- DO NOT EDIT.\n"
    "Edit design/tokens.json, re-run the generator, commit both."
)


def load():
    with open(TOKENS) as f:
        t = json.load(f)
    palette = {k: v for k, v in t["palette"].items() if not k.startswith("_")}
    roles = {k: v for k, v in t["roles"].items() if not k.startswith("_")}
    surfaces = {k: v for k, v in t["surfaces"].items() if not k.startswith("_")}
    shape = {k: v for k, v in t["shape"].items() if not k.startswith("_")}
    spacing = {k: v for k, v in t["spacing"].items() if not k.startswith("_")}
    for role, ref in roles.items():
        if ref not in palette:
            sys.exit(f"tokens.json: role '{role}' references unknown palette color '{ref}'")
    return palette, roles, surfaces, shape, spacing


def hex6(s):
    s = s.lstrip("#")
    if len(s) != 6:
        sys.exit(f"tokens.json: expected 6-digit hex, got '{s}'")
    return s.upper()


def gen_swift(palette, roles, surfaces, shape, spacing):
    L = []
    for line in HEADER.split("\n"):
        L.append(f"// {line}")
    L += [
        "",
        "import SwiftUI",
        "import UIKit",
        "",
        "/// Semantic colors of the TinkerRocket design language.  iOS is the",
        "/// design reference: these are the Apple system-color values the app",
        "/// has always used, lifted into named roles so Android renders the",
        "/// exact same hex (see the twin generated DesignTokens.kt).",
        "enum TRColor {",
    ]
    for role, ref in roles.items():
        c = palette[ref]
        L.append(
            f"    static let {role} = dynamic(0x{hex6(c['light'])}, "
            f"0x{hex6(c['dark'])})  // {ref}"
        )
    L.append("")
    for name, c in surfaces.items():
        L.append(
            f"    static let {name} = dynamic(0x{hex6(c['light'])}, "
            f"0x{hex6(c['dark'])})"
        )
    L += [
        "",
        "    private static func dynamic(_ light: UInt32, _ dark: UInt32) -> Color {",
        "        Color(UIColor { traits in",
        "            let v = traits.userInterfaceStyle == .dark ? dark : light",
        "            return UIColor(",
        "                red: CGFloat((v >> 16) & 0xFF) / 255.0,",
        "                green: CGFloat((v >> 8) & 0xFF) / 255.0,",
        "                blue: CGFloat(v & 0xFF) / 255.0,",
        "                alpha: 1.0)",
        "        })",
        "    }",
        "}",
        "",
        "enum TRShape {",
    ]
    for name, v in shape.items():
        L.append(f"    static let {name}: CGFloat = {v}")
    L += ["}", "", "enum TRSpacing {"]
    for name, v in spacing.items():
        L.append(f"    static let {name}: CGFloat = {v}")
    L += ["}", ""]
    return "\n".join(L)


def gen_kotlin(palette, roles, surfaces, shape, spacing):
    def color(c):
        return f"Color(0xFF{hex6(c)})"

    L = []
    for line in HEADER.split("\n"):
        L.append(f"// {line}")
    L += [
        "",
        "package com.tinkerbug.tinkerrocket.app.theme",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.unit.Dp",
        "import androidx.compose.ui.unit.dp",
        "",
        "/**",
        " * Semantic colors of the TinkerRocket design language.  iOS is the",
        " * design reference: these are the Apple system-color values the iOS",
        " * app renders, so the two apps match hue for hue (twin generated",
        " * file: DesignTokens.swift).  Screens reach for roles, never raw",
        " * palette colors.",
        " */",
        "class TrColors(",
    ]
    for role in roles:
        L.append(f"    val {role}: Color,")
    for name in surfaces:
        L.append(f"    val {name}: Color,")
    L += [")", "", "val TrColorsLight = TrColors("]
    for role, ref in roles.items():
        L.append(f"    {role} = {color(palette[ref]['light'])},  // {ref}")
    for name, c in surfaces.items():
        L.append(f"    {name} = {color(c['light'])},")
    L += [")", "", "val TrColorsDark = TrColors("]
    for role, ref in roles.items():
        L.append(f"    {role} = {color(palette[ref]['dark'])},  // {ref}")
    for name, c in surfaces.items():
        L.append(f"    {name} = {color(c['dark'])},")
    L += [")", "", "object TrShape {"]
    for name, v in shape.items():
        L.append(f"    val {name}: Dp = {v}.dp")
    L += ["}", "", "object TrSpacing {"]
    for name, v in spacing.items():
        L.append(f"    val {name}: Dp = {v}.dp")
    L += ["}", ""]
    return "\n".join(L)


def main():
    check = "--check" in sys.argv
    palette, roles, surfaces, shape, spacing = load()
    outputs = {
        SWIFT_OUT: gen_swift(palette, roles, surfaces, shape, spacing),
        KOTLIN_OUT: gen_kotlin(palette, roles, surfaces, shape, spacing),
    }
    stale = []
    for path, content in outputs.items():
        rel = path.relative_to(ROOT)
        current = path.read_text() if path.exists() else None
        if current == content:
            print(f"  ok {rel}: unchanged")
        elif check:
            stale.append(rel)
            print(f"  X  {rel}: STALE")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"  ->  {rel}: wrote")
    if stale:
        print("Design tokens are out of date with design/tokens.json.")
        print("Run:  python3 tools/gen_design_tokens.py")
        print("and commit the result.")
        sys.exit(1)


if __name__ == "__main__":
    main()
