#!/usr/bin/env python3
"""
Generate the firmware navigation index from `// SECTION:` banners.

The three firmware entry points are single files of 5,000-7,500 lines each.
There is no module boundary to navigate by, so the source itself carries the
map: a `// SECTION: <title>` banner marks the start of each logical region,
and this script turns those banners into a Markdown table of line ranges with
GitHub permalinks.

Generating it (rather than writing it by hand) is the whole point -- a
hand-written line-range table is stale the first time anyone inserts a
function, and a stale map is worse than none. CI runs `--check`, so the
committed index and the committed source can never disagree.

Usage:
    python3 tools/gen_section_index.py            # rewrite the index files
    python3 tools/gen_section_index.py --check    # exit 1 if any is stale

To add a section, put a banner in the source and re-run; nothing here needs
editing. To add a whole firmware, add an entry to TARGETS.
"""

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REPO_URL = "https://github.com/Tinkerbug-Robotics/TinkerRocket"
BRANCH = "main"

# (source file, generated index file, human name)
TARGETS = [
    ("tinkerrocket-idf/projects/out_computer/main/main.cpp",
     "docs/architecture/generated/out-computer-map.md",
     "Out Computer"),
    ("tinkerrocket-idf/projects/flight_computer/main/main.cpp",
     "docs/architecture/generated/flight-computer-map.md",
     "Flight Computer"),
    ("tinkerrocket-idf/projects/base_station/main/main.cpp",
     "docs/architecture/generated/base-station-map.md",
     "Base Station"),
]

SECTION_RE = re.compile(r"^\s*// SECTION:\s*(.+?)\s*$")
BANNER_RULE_RE = re.compile(r"^\s*// ={10,}\s*$")

HEADER = """<!-- GENERATED by tools/gen_section_index.py -- do not edit by hand. -->
<!-- Regenerate with: python3 tools/gen_section_index.py -->

# {name} -- `main.cpp` navigation map

`{src}` is {total:,} lines in one translation unit. These are the
`// SECTION:` banners in it, in file order. Line counts include each
section's banner and leading comments.

| Section | Lines | Span |
|---------|-------|------|
"""

FOOTER = """
Total: {n} sections across {total:,} lines.
"""


def parse_sections(text):
    """Return [(title, start_line, end_line)] 1-based inclusive, file order.

    A section starts at its banner's top rule (so the banner itself is
    counted with the section it introduces) and runs to the line before the
    next banner, or EOF.
    """
    lines = text.splitlines()
    hits = []
    for i, line in enumerate(lines):
        m = SECTION_RE.match(line)
        if not m:
            continue
        start = i
        # Step up over the banner's top rule so the range starts at the box.
        if i > 0 and BANNER_RULE_RE.match(lines[i - 1]):
            start = i - 1
        hits.append((m.group(1), start))

    out = []
    for n, (title, start) in enumerate(hits):
        end = hits[n + 1][1] - 1 if n + 1 < len(hits) else len(lines) - 1
        out.append((title, start + 1, end + 1))
    return out, len(lines)


def render(src_rel, name, sections, total):
    rows = []
    for title, start, end in sections:
        url = f"{REPO_URL}/blob/{BRANCH}/{src_rel}#L{start}-L{end}"
        rows.append(f"| [{title}]({url}) | {end - start + 1:,} | {start}-{end} |")
    return (HEADER.format(name=name, src=src_rel, total=total)
            + "\n".join(rows)
            + "\n"
            + FOOTER.format(n=len(sections), total=total))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the committed index matches the source; do not write")
    args = ap.parse_args()

    stale, written, skipped = [], [], []

    for src_rel, out_rel, name in TARGETS:
        src = REPO / src_rel
        out = REPO / out_rel
        if not src.exists():
            print(f"  ?  {src_rel}: missing, skipped")
            continue

        sections, total = parse_sections(src.read_text())
        if not sections:
            skipped.append(name)
            print(f"  -  {name}: no // SECTION: banners yet, skipped")
            continue

        want = render(src_rel, name, sections, total)
        have = out.read_text() if out.exists() else None

        if args.check:
            if have != want:
                stale.append(out_rel)
                print(f"  X  {out_rel}: STALE ({len(sections)} sections in source)")
            else:
                print(f"  ok {out_rel}: {len(sections)} sections")
        else:
            if have == want:
                print(f"  ok {out_rel}: unchanged ({len(sections)} sections)")
            else:
                out.parent.mkdir(parents=True, exist_ok=True)
                out.write_text(want)
                written.append(out_rel)
                print(f"  ->  {out_rel}: wrote {len(sections)} sections")

    if args.check and stale:
        print("\nSection index is out of date with the source.\n"
              "Run:  python3 tools/gen_section_index.py\n"
              "and commit the result.", file=sys.stderr)
        return 1
    if skipped:
        print(f"\nNot yet bannered: {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
